model_name : 'gat'
dataset_name: 'citeseer'
model_params:
  num_layers: 2
  hidden_dim: 64
  num_heads: 8
  drop_out: 0.6
  
dataset_params:
  data_path: 'data'

optim_name: 'adam'
optim_params:
  lr: 0.001